name: pretty-plot
channels:
# note: packages _must_ be installed from conda-forge. defaults has a newer/incompatible version of libgsl.
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - clize
  - marslab
  - fs
