name: pretty-plot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - git
  - jupyter
  - clize
  - pip
  - gdal
  - rasterio
  - pvl
  - python-Levenshtein
  - scipy
  - scikit-image
  - pip:
      - git+https://github.com/MillionConcepts/pdr.git
  - astropy
  - sympy
