name: pretty-plot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - git
  - jupyter
  - clize
  - python-Levenshtein
  - scipy
  - scikit-image
  - pdr
  - astropy
  - sympy
  - marslab
