name: pretty_plot
channels:
# note: packages _must_ be installed from conda-forge. defaults has a newer/incompatible version of libgsl.
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - fire
  - marslab
  - fs
